# Generated by Django 4.2.7 on 2026-05-31 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issued_by', models.CharField(max_length=200)),
                ('cert_type', models.CharField(choices=[('internship', 'Internship Certificate'), ('experience', 'Experience Certificate'), ('training', 'Training Certificate'), ('course', 'Course Certificate'), ('achievement', 'Achievement')], default='internship', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='Upload PDF or image of the certificate', upload_to='certificates/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional preview image of the certificate', null=True, upload_to='certificates/thumbs/')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('credential_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('board_university', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pursuing', 'Pursuing'), ('Completed', 'Completed')], default='Completed', max_length=30)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('whatsapp', models.CharField(blank=True, max_length=25)),
                ('location', models.CharField(max_length=150)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, help_text='Upload your profile photo (JPG/PNG, square recommended)', null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, help_text='Upload your latest resume (PDF)', null=True, upload_to='resume/')),
                ('years_experience', models.PositiveIntegerField(default=1)),
                ('projects_count', models.PositiveIntegerField(default=5)),
                ('internships_count', models.PositiveIntegerField(default=2)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma-separated list, e.g. Python, Django, React', max_length=400)),
                ('thumbnail', models.ImageField(blank=True, help_text='Project screenshot or banner (16:9 recommended)', null=True, upload_to='projects/')),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('development', 'In Development'), ('completed', 'Completed')], default='completed', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField(default=80, help_text='0-100')),
                ('icon_url', models.URLField(blank=True, help_text='DevIcon / custom image URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('company_url', models.URLField(blank=True)),
                ('duration', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(help_text='One bullet point per line')),
                ('exp_type', models.CharField(choices=[('internship', 'Internship'), ('fulltime', 'Full-time'), ('training', 'Training'), ('freelance', 'Freelance')], default='internship', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('certificate', models.ForeignKey(blank=True, help_text='Attach the internship/experience certificate for this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='portfolio.certificate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
