export const FALLBACK = {
  profile: {
    name:"Vishal Gupta", title:"Backend Developer · Python Engineer",
    tagline:"Building scalable APIs & robust backend systems",
    summary:"Results-driven Python Backend Developer with hands-on experience designing scalable REST APIs using Django & Django REST Framework. Proficient in MySQL/SQLite database design, third-party API integration, and clean-code principles.",
    email:"vg016600@gmail.com", phone:"+91 88405 58318",
    whatsapp:"+918840558318", location:"Lucknow, Uttar Pradesh, India",
    github:"https://github.com/Vishal5725",
    linkedin:"https://www.linkedin.com/in/vgpython884055",
    portfolio_url:"https://vish22portfolio.pythonanywhere.com/api/portfolio/",
    photo_url:null, resume_url:null,
    years_experience:1, projects_count:5, internships_count:2, is_available:true,
  },
  skill_categories:[
    {id:1,name:"Backend & Core",icon:"⚙️",skills:[
      {id:1,name:"Python",percentage:92},{id:2,name:"Django",percentage:88},
      {id:3,name:"Django REST Framework",percentage:87},
      {id:4,name:"REST API Development",percentage:88},
      {id:5,name:"MySQL",percentage:83},{id:6,name:"SQLite",percentage:80},
      {id:7,name:"Git & GitHub",percentage:85},{id:8,name:"JWT Auth",percentage:80},
    ]},
    {id:2,name:"Frontend (Supporting)",icon:"🎨",skills:[
      {id:9,name:"HTML5",percentage:78},{id:10,name:"CSS3",percentage:72},
      {id:11,name:"Bootstrap",percentage:70},{id:12,name:"React (Basic)",percentage:65},
    ]},
    {id:3,name:"Tools & Practices",icon:"🛠️",skills:[
      {id:13,name:"API Integration",percentage:85},{id:14,name:"Postman",percentage:82},
      {id:15,name:"Linux / CLI",percentage:75},{id:16,name:"Agile / Scrum",percentage:70},
    ]},
  ],
  projects:[
    {id:1,title:"Borrow Management System",subtitle:"React frontend + Django REST API",
      description:"Full-featured borrow management app — React frontend on Vercel + Django REST Framework backend with JWT auth, CRUD operations, and a responsive dashboard.",
      tech_list:["React","Django","DRF","JWT","MySQL","Axios","Vercel"],
      live_url:"https://rajupanshop-pvw8jpqcn-vishal5725s-projects.vercel.app/login",
      github_url:"https://github.com/Vishal5725",
      status:"live",featured:true,thumbnail_url:null},
    {id:2,title:"E-Commerce Website",subtitle:"Django MVT full-stack online store",
      description:"Complete e-commerce app on Django MVT: product catalogue, cart, orders, user auth, admin dashboard. Deployed live on PythonAnywhere.",
      tech_list:["Python","Django","SQLite","Bootstrap","HTML","CSS","PythonAnywhere"],
      live_url:"https://vish221305.pythonanywhere.com/",
      github_url:"https://github.com/Vishal5725",
      status:"live",featured:true,thumbnail_url:null},
    {id:3,title:"Personal Portfolio API",subtitle:"RESTful API — live on PythonAnywhere",
      description:"Production-deployed Django REST API powering this portfolio, with DRF viewsets, CORS, and a browsable interface.",
      tech_list:["Django","DRF","SQLite","CORS","PythonAnywhere"],
      live_url:"https://vish22portfolio.pythonanywhere.com/api/portfolio/",
      github_url:"https://github.com/Vishal5725",
      status:"live",featured:true,thumbnail_url:null},
    {id:4,title:"Task Management API",subtitle:"Full CRUD backend with JWT & RBAC",
      description:"Task management backend with JWT, role-based access, indexed MySQL schema, and DRF-documented endpoints.",
      tech_list:["Python","Django","DRF","MySQL","JWT"],
      github_url:"https://github.com/Vishal5725",
      status:"completed",featured:false,thumbnail_url:null},
  ],
  experiences:[
    {id:1,role:"Backend Developer Intern",company:"BTM",
     duration:"6 Months",exp_type:"internship",certificate:null,
     bullet_points:[
       "Engineered robust RESTful APIs with Django REST Framework; improved query performance through ORM optimisation.",
       "Designed normalised MySQL schemas for high-traffic data operations with cross-functional teams.",
       "Integrated third-party APIs to streamline data exchange, reducing manual processing time significantly.",
       "Delivered PEP 8-compliant code; participated in peer code reviews, reducing team bug rate.",
       "Deployed Django apps to production and performed debugging & performance profiling.",
     ]},
    {id:2,role:"Backend Developer Intern",company:"BYTO",
     duration:"6 Months",exp_type:"internship",certificate:null,
     bullet_points:[
       "Architected and deployed REST APIs using Django & DRF for both web and mobile clients.",
       "Implemented JWT auth and role-based access control across all API endpoints.",
       "Authored Python automation scripts eliminating ~40% manual effort per sprint.",
       "Managed SQLite & MySQL databases; wrote optimised queries for analytics dashboards.",
       "Participated in Agile sprints; consistently delivered tasks on schedule.",
     ]},
    {id:3,role:"Python Programming Trainee",company:"Techpile Technology, Lucknow",
     duration:"45 Days",exp_type:"training",certificate:null,
     bullet_points:[
       "Completed intensive Python training: fundamentals, OOP, Django basics.",
       "Built CLI projects and a web scraper applying real-world concepts.",
       "Gained foundational exposure to Django and SQLite interactions.",
     ]},
  ],
  education:[
    {id:1,degree:"B.Tech – Computer Science Engineering",
     institution:"LDC Group of Institute of Technologies",board_university:"AKTU",
     duration:"Pursuing",status:"Pursuing"},
    {id:2,degree:"Polytechnic Diploma – CSE",
     institution:"Govt. Polytechnic Aurai, Bhadohi",board_university:"BTEUP",
     duration:"Completed",status:"Completed"},
    {id:3,degree:"Intermediate – 12th (UP Board)",
     institution:"Govt. Inter College Gyanpur, Bhadohi",board_university:"UP Board",
     duration:"Completed",status:"Completed"},
    {id:4,degree:"High School – 10th (UP Board)",
     institution:"Govt. Inter College Gyanpur, Bhadohi",board_university:"UP Board",
     duration:"Completed",status:"Completed"},
  ],
  certifications:[
    {id:1,title:"Python Summer Training",issuer:"Techpile Technology",year:"2023"},
    {id:2,title:"Django REST Framework",issuer:"Self-Driven Learning",year:"2023"},
    {id:3,title:"Git & GitHub Version Control",issuer:"Online Course",year:"2023"},
    {id:4,title:"Backend Development Best Practices",issuer:"Self-Learning",year:"2024"},
  ],
  certificates:[],
};
